# .github/workflows/sync.yml
name: Rebase Upstream
on:
  schedule:
  - cron: "0 8 * * *"  # “At 08:00.” 
  workflow_dispatch:   # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        branch: nixos-unstable
    - uses: imba-tjd/rebase-upstream-action@master
      # with:  # all args are optional
      #   upstream: <user>/<repo>
      #   branch:   master
